### ISSUE TITLE
Fix bcompiler-init

### ISSUE THREAD

**Issue by yulqen** [yulqen/bcompiler#5]
`bcompiler-init` currently fails if the user does not have `Documents/bcompiler/source` directory available. Does't `bcompiler-init` create that direct if it does not exist??

**Comment by hammerheadlemon** [comment]
A key question here is whether `bcompiler` does in fact require its own `config.ini` file. Certainly the git repository stuff associated with the datamap and associated files is no longer needed as that was never used.
